### ISSUE TITLE
Shorten the version hash

### ISSUE THREAD

**Issue by drewr** [elastic/runbld#10]
First 7 bytes will suffice, like GitHub does it.

**Comment by elasticdog** [comment]
The first 7 bytes is not a great choice [1] and Git will actually display the appropriate length when abbreviating to ensure a unique hash (it's not a static value)...although that doesn't prevent future collisions.

TL;DR pick the first 12 bytes for a decent future-proof value.

[1] [How short can Git abbreviate?](http://blog.cuviper.com/2013/11/10/how-short-can-git-abbreviate/)

**Comment by drewr** [comment]
Interesting! Thanks @elasticdog. :musical_note:

**Comment by drewr** [comment]
BTW, I wasn't talking about shortening the one that we store in ES, just the vanity one in the email templates.

**Comment by drewr** [comment]
Oh! And it's not the commit that the process's build is based on, it's for the runbld version display.
