### ISSUE TITLE
Add a link to build-stats.elastic.co for lucene-ci build failures

### ISSUE THREAD

**Issue by romseygeek** [elastic/runbld#141]
Currently we just get a link to the Jenkins build, but this vanishes fairly quickly as there are a lot of lucene builds.

See https://github.com/elastic/infra/pull/3719

**Comment by elasticdog** [comment]
It would be ideal if we could get a link to both the metadata and the console output (for all jobs, not just lucene) included in the failure notifications. For instance:

* [build metadata](https://build-stats.elastic.co/app/kibana#/doc/build-*/build-1498188341992/t?id=20180127070317-9FA6B7B5&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now)))
* [console output](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(log),filters:!(('$$hashKey':'object:2070','$state':(store:appState),meta:(alias:!n,disabled:!f,index:'log-*',key:build-id,negate:!f,value:'20180127070317-9FA6B7B5'),query:(match:(build-id:(query:'20180127070317-9FA6B7B5',type:phrase))))),index:'log-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'*')),sort:!(time,desc)))
