### ISSUE TITLE
Unexplained stalling when build fails

### ISSUE THREAD

**Issue by spalger** [elastic/runbld#142]
Not sure what could be causing this but I'm seeing some unexplained stalling in some builds on failure. Checkout the timestamps [from this job](https://kibana-ci.elastic.co/view/All/job/elastic+esvm-snapshot-builder+jenkins+periodic/64/ES_BRANCH=master,node=linux/console):

```
          00:01:20.123 BUILD FAILED in 59s
          00:01:23.392 runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
          00:01:23.392 runbld>>> DURATION: 66451ms
          00:01:23.392 runbld>>> STDOUT: 2038 bytes
          00:01:23.392 runbld>>> STDERR: 26309 bytes
          00:01:23.393 runbld>>> WRAPPED PROCESS: FAILURE (1)
          00:01:23.393 runbld>>> Searching for build metadata in /var/lib/jenkins/workspace/elastic+esvm-snapshot-builder+jenkins+periodic/ES_BRANCH/master/node/linux
          00:01:24.215 runbld>>> Storing build metadata: 
          00:01:27.495 runbld>>> BUILD: https://5086a1f436ee16623a447bdf25881bbc.us-east-1.aws.found.io:9243/build-1498188341992/t/20180202211613-FC4B48A2
 +4.5 min 00:06:05.989 runbld>>> MAILING: build-kibana@e***.co
          00:06:06.330 runbld>>> Mail sent.  Output: {:code 0, :error :SUCCESS, :message "messages sent"}
          00:06:06.330 
 +1.5 min 00:07:37.354 runbld>>> NOTIFYING SLACK
          00:07:42.577 Build step 'Execute shell' marked build as failure
          00:07:42.621 Skipped archiving because build is not successful
```

Any idea what's going on?

**Comment by tylerjl** [comment]
Given that the ~5 minute delay occurs around the "Storing build metadata" part, I assume the delay is being incurred by indexing the build results into Cloud. We had some cluster difficulties a while back but I don't see other jobs suffering from similar long execution times, @leathekd as our `runbld` poobah do you know whether this is something potentially runbld-related or just the remote cluster being janky?
