### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by elasticdog** [elastic/runbld#148]
I first noticed this warning at the bottom of the [packaging tests](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/2484/console) builds for ES, at the end of the job run right after runbld stores the build metadata.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by clojure.lang.Reflector (file:/usr/local/src/runbld-1.5.11/runbld) to method com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(org.xml.sax.InputSource,org.xml.sax.helpers.DefaultHandler)
WARNING: Please consider reporting this to the maintainers of clojure.lang.Reflector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Anything we can work around, or do we need to report something upstream?

**Comment by ddillinger** [comment]
It's scheduled for clojure 1.10 https://dev.clojure.org/jira/browse/CLJ-2066

**Comment by ddillinger** [comment]
It may be possible to add type hints, maybe running it with `--illegal-access=debug` will show the call site
