### ISSUE TITLE
Fix JAVA_HOME discovery on OS X

### ISSUE THREAD

**Issue by drewr** [elastic/runbld#30]
The path structure on OS X JDKs is :hankey:

**Comment by jasontedor** [comment]
Have you tried using `/usr/libexec/java_home -v ${version}` with `version` equal to 1.7 or 1.8 or 9 to get the clean path to the JDK home?

**Comment by drewr** [comment]
@jasontedor That's one way, yes, but then it's tied to OS X.  We do some more introspection that's platform-independent we can reuse here.
