### ISSUE TITLE
Job name parsing is skipping the first plus (+)

### ISSUE THREAD

**Issue by elasticdog** [elastic/runbld#4]
If you look at the attached email generated by runbld, the job name isn't parsed quite correctly into its parts...my understanding is the jobs should now be `user + project + branch + meta-data`.

![screen shot 2015-12-18 at 7 14 15 am](https://cloud.githubusercontent.com/assets/4742/11900224/3ab091c0-a559-11e5-8885-92022af230c5.png)

```
JOB NAME
    elastic+elasticsearch+master+multijob-intake

EXPECTED
    user:      elastic
    project:   elasticsearch
    branch:    master
    meta-data: multijob-intake

ACTUAL
    user:      elastic+elasticsearch
    project:   master
    branch:    multijob-intake
    meta-data: <none>
```

Is my assumed format no longer correct? I am actually using the metadata field for establishing the different phases of a single top-level job, and there's a regex being used to create the various Jenkins "views" to keep things organized.

*BTW, the new output is amazing! The summary and parsed out/attached errors is awesome.*

**Comment by drewr** [comment]
It's a bug, fixed but not yet pushed!

And thanks :grin:

**Comment by drewr** [comment]
Reopening, want to make sure it closes from the commit....

**Comment by elasticdog** [comment]
Doh, sorry for jumping the gun.
