### ISSUE TITLE
Clarify in console which output is runbld

### ISSUE THREAD

**Issue by drewr** [elastic/runbld#45]
There's a lot going on in a build. Lots of software interacting. Right now runbld throws around some lines that aren't labeled and it can be confusing to build consumer.

**Comment by michaelbaamonde** [comment]
Can we close this, given https://github.com/elastic/runbld/commit/49e22d5637014eb6b9f1060c4d6248e4a4e1834c?

**Comment by drewr** [comment]
Once that's merged, this should auto-close.  It's in a branch that isn't live yet.

**Comment by michaelbaamonde** [comment]
Ah, missed that the branch isn't merged yet.
