### ISSUE TITLE
Catch Slack exceptions

### ISSUE THREAD

**Issue by drewr** [elastic/runbld#46]
Slack was down when [this build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/1112/console) ended.  The http response threw an exception, which polluted the console with the raw object.  Let's do this:

1. Retry on notification failures
1. Print a one-line notification instead of bubbling up the exception

**Comment by nik9000** [comment]
Sounds good to me! Thanks for opening this.
