### ISSUE TITLE
Set a default SCM branch based on the parsed project name

### ISSUE THREAD

**Issue by elasticdog** [elastic/runbld#70]
Just capturing the issue here to provide some context to the work that @leathekd is doing...

When using runbld to clone a Git repository, you must currently hard-code the branch name in the SCM config (or via command line parameters), which means a lot of [duplicated definitions](https://github.com/elastic/infra/blob/e6e20a4757d8410f94253165a32e3025db0cb902/ansible/roles/runbld/templates/runbld.conf.j2#L118-L130). This also becomes a maintenance problem when branches are added/removed from our Jenkins Job Builder definitions, as the list of branches must be kept in sync.

Since runbld already has a built-in understanding of the branch based on parsing our standardized job name, we can use that as a sane default value for the SCM config, and only override it (via the config file or command line parameter) when explicitly needed. This will allow us to have a less-specific regex in the _runbld.conf_ file that does not hard-code each branch name, which reduces duplication, and means we don't have to maintain the same list of branches in two separate locations.

**Comment by michaelbaamonde** [comment]
+1, good idea. I originally thought about doing this, but went with the naive approach to get something working quickly.

**Comment by leathekd** [comment]
Yeah, it's not far off.  The test is likely to be more work than the actual change.
