### ISSUE TITLE
Add the ability to kill a build after a timeout

### ISSUE THREAD

**Issue by leathekd** [elastic/runbld#76]
Time to time the underlying build process will get wedged and will need to be manually killed from Jenkins.  In this case we lose some information about the build.  With #75 we will at least know that the build started, but it might also be useful to have per project config for build timeouts in runbld (as well as a global default?).  We can then store when/if a build is killed for taking too long.

**Comment by elasticdog** [comment]
Great idea! The less reliance on Jenkins functionality the better.

**Comment by leathekd** [comment]
https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#waitFor-long-java.util.concurrent.TimeUnit-

**Comment by drewr** [comment]
I like it, should make it configurable, since for some jobs a few minutes is a long time and for others a few hours.
